-- Inserimenti dei cuochi
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) VALUES(nextval('cuoco_seq'), 'Bruno', 'Barbieri', '1962-01-12', '/images/cuochi/Bruno-Barbieri.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) VALUES(nextval('cuoco_seq'), 'Joe', 'Bastianich', '1968-09-17', '/images/cuochi/Joe-Bastianich.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) VALUES(nextval('cuoco_seq'), 'Antonino', 'Cannavacciuolo', '1975-11-21', '/images/cuochi/Antonino-Cannavacciuolo.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) VALUES(nextval('cuoco_seq'), 'Carlo', 'Cracco', '1965-10-08', '/images/cuochi/Carlo-Cracco.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) VALUES(nextval('cuoco_seq'), 'Gordon', 'Ramsay', '1966-11-08', '/images/cuochi/Gordon-Ramsay.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) VALUES(nextval('cuoco_seq'), 'Max', 'Mariola', '1976-05-18', '/images/cuochi/Max-Mariola.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) VALUES(nextval('cuoco_seq'), 'Massimo', 'Bottura', '1962-09-30', '/images/cuochi/Massimo-Bottura.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) VALUES(nextval('cuoco_seq'), 'Gennaro', 'Contaldo', '1949-01-21', '/images/cuochi/Gennaro-Contaldo.jpeg');

-- Inserimenti delle ricette
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Cacio e Pepe', 'La nostra cacio e pepe è un omaggio alla tradizione culinaria romana, un piatto che incarna l essenza della cucina italiana con pochi e semplici ingredienti. La pasta, al dente e avvolta in una crema vellutata di pecorino romano e pepe nero macinato al momento, trasporta i vostri sensi direttamente nelle stradine acciottolate di Roma. La combinazione di formaggio stagionato e piccante pepe nero crea un equilibrio di sapori robusti e intensi che si sposano armoniosamente con la pasta, regalando un esperienza gustativa autentica e appagante. Preparata con maestria e amore per la cucina tradizionale, la nostra cacio e pepe vi regalerà un viaggio sensoriale unico, dove ogni forchettata è un esplosione di gusto e nostalgia per i sapori genuini della cucina italiana', (SELECT id FROM cuoco WHERE nome = 'Joe' AND cognome = 'Bastianich'), '{/images/ricette/CacioePepe.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Lasagna', 'La nostra deliziosa lasagna è un tripudio di sapori italiani che conquista il palato ad ogni morso. Strati di pasta fresca si alternano con una salsa di pomodoro ricca e saporita, arricchita da carne macinata finemente aromatizzata con spezie mediterranee. Un abbraccio cremoso di besciamella avvolge il tutto, impreziosito da generose porzioni di formaggio mozzarella e parmigiano che si fondono in un mare di filantezza al primo taglio. Gli strati di verdure fresche donano freschezza e consistenza, creando un equilibrio perfetto di gusto e texture. Preparata con amore e passione, la nostra lasagna è un capolavoro culinario che conquisterà il cuore di ogni gourmet e delizierà le tavole di famiglie e amici. Semplice da preparare ma ricca di soddisfazioni, questa lasagna sarà la protagonista indiscussa delle vostre cene memorabili.', (SELECT id FROM cuoco WHERE nome = 'Bruno' AND cognome = 'Barbieri'), '{/images/ricette/Lasagna.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Tiramisù', 'Il nostro tiramisù è un autentico capolavoro della pasticceria italiana, un dolce che incanta i palati di chiunque lo assaggi. Strati di savoiardi imbevuti nel caffè si alternano con una crema di mascarpone delicata e vellutata, creando un equilibrio perfetto di dolcezza e intensità. Una leggera spolverata di cacao amaro completa questo dessert, regalando un contrasto piacevole di sapori e una nota finale elegante. Preparato con cura e passione, il nostro tiramisù è un omaggio alla tradizione culinaria italiana, capace di trasportare chi lo assapora in un viaggio di piacere e nostalgia. Perfetto da gustare in ogni occasione, questo tiramisù conquisterà il cuore di tutti gli amanti del buon cibo.', (SELECT id FROM cuoco WHERE nome = 'Carlo' AND cognome = 'Cracco'), '{/images/ricette/Tiramisu.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Risotto ai Funghi', 'Il nostro risotto ai funghi è una delizia culinaria che unisce la cremosità del riso Carnaroli con il gusto intenso dei funghi porcini. La base di brodo vegetale, arricchita da una selezione di erbe aromatiche, conferisce al piatto un sapore ricco e avvolgente. I funghi, delicatamente saltati in padella con aglio e prezzemolo, aggiungono profondità e complessità al risotto, creando un equilibrio perfetto di sapori terrosi e cremosità. La mantecatura finale con burro e parmigiano reggiano conferisce al piatto una consistenza vellutata e un sapore avvolgente che conquisterà ogni palato. Preparato con maestria e passione, il nostro risotto ai funghi è un esperienza gastronomica indimenticabile che vi farà innamorare della cucina italiana.', (SELECT id FROM cuoco WHERE nome = 'Gordon' AND cognome = 'Ramsay'), '{/images/ricette/RisottoFunghi.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Spaghetti Carbonara', 'La nostra versione della classica carbonara è un tripudio di sapori italiani che conquista il palato ad ogni forchettata. Spaghetti al dente si sposano con una crema vellutata di uova, pecorino romano e guanciale croccante, creando un equilibrio perfetto di gusto e consistenza. Il tocco finale di pepe nero macinato al momento aggiunge una nota di vivacità e intensità al piatto, rendendolo un esperienza gastronomica indimenticabile. Preparata con cura e passione, la nostra carbonara vi trasporterà direttamente nelle trattorie romane, regalandovi un viaggio sensoriale unico e appagante.', (SELECT id FROM cuoco WHERE nome = 'Joe' AND cognome = 'Bastianich'), '{/images/ricette/Carbonara.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Pizza Margherita', 'La nostra pizza Margherita è un omaggio alla tradizione napoletana, un simbolo della cucina italiana nel mondo intero. La base sottile e croccante, arricchita da una salsa di pomodoro fresco e basilico profumato, è coronata da generose fette di mozzarella di bufala che si fondono armoniosamente con gli altri ingredienti. Un filo d olio extravergine d oliva e una spolverata di sale marino completano questo capolavoro culinario, regalando un esplosione di sapori mediterranei ad ogni morso. Preparata con ingredienti di alta qualità e passione per la tradizione, la nostra pizza Margherita vi conquisterà con la sua semplicità e bontà, trasportandovi direttamente nei vicoli di Napoli.', (SELECT id FROM cuoco WHERE nome = 'Carlo' AND cognome = 'Cracco'), '{/images/ricette/PizzaMargherita.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Filetto di Manzo al Pepe Verde', 'Il nostro filetto di manzo al pepe verde è un piatto iconico che unisce la tenerezza della carne alla intensità del pepe verde. La carne, tagliata con precisione e cotta alla perfezione, si accoppia con una salsa cremosa e profumata al pepe verde che esalta il suo sapore e la sua morbidezza. Un contorno di verdure di stagione e patate al forno completa questo piatto, creando un equilibrio di gusto e texture che conquista ogni palato. Preparato con ingredienti freschi e di alta qualità, il nostro filetto di manzo al pepe verde è un esperienza culinaria indimenticabile che vi farà apprezzare la semplicità e leleganza della cucina italiana.', (SELECT id FROM cuoco WHERE nome = 'Bruno' AND cognome = 'Barbieri'), '{/images/ricette/FilettoManzo.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Gnocchi al Gorgonzola', 'I nostri gnocchi al gorgonzola sono un piatto irresistibile che unisce la delicatezza degli gnocchi alla cremosità e al sapore deciso del formaggio gorgonzola. Gli gnocchi, realizzati con patate fresche e farina di alta qualità, si sposano armoniosamente con una salsa cremosa di gorgonzola che avvolge ogni boccone in un abbraccio di gusto e piacere. Una spolverata di noci tritate aggiunge croccantezza e un tocco di sapore aggiuntivo al piatto, creando un equilibrio perfetto di sapori e consistenze. Preparati con cura e maestria, i nostri gnocchi al gorgonzola sono un esperienza gastronomica da gustare e condividere con chiunque ami la buona cucina italiana.', (SELECT id FROM cuoco WHERE nome = 'Gordon' AND cognome = 'Ramsay'), '{/images/ricette/GnocchiGorgonzola.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Pasta alla Norma', 'La nostra Pasta alla Norma è un omaggio alla tradizione siciliana. La pasta al dente si mescola con una salsa di pomodoro ricca e saporita, arricchita da melanzane fritte e ricotta salata grattugiata. Un piatto semplice ma ricco di sapori mediterranei, perfetto per un pranzo estivo.', (SELECT id FROM cuoco WHERE nome = 'Antonino' AND cognome = 'Cannavacciuolo'), '{/images/ricette/PastaAllaNorma.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Arancini di Riso', 'I nostri arancini di riso sono una prelibatezza siciliana. Palline di riso ripiene di ragù, piselli e mozzarella, fritte fino a doratura perfetta. Un antipasto croccante fuori e morbido dentro, perfetto per ogni occasione.', (SELECT id FROM cuoco WHERE nome = 'Max' AND cognome = 'Mariola'), '{/images/ricette/AranciniDiRiso.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Panna Cotta al Caramello', 'La nostra panna cotta al caramello è un dolce elegante e raffinato. La panna cotta, morbida e vellutata, si accompagna con un delizioso caramello fatto in casa. Un dessert perfetto per concludere una cena in modo dolce e soddisfacente.', (SELECT id FROM cuoco WHERE nome = 'Massimo' AND cognome = 'Bottura'), '{/images/ricette/PannaCottaCaramello.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Zuppa di Pesce', 'La nostra zuppa di pesce è un tripudio di sapori marini. Un ricco brodo di pomodoro accoglie una varietà di pesci freschi, cozze, vongole e gamberi. Un piatto che porta i profumi del mare direttamente sulla vostra tavola.', (SELECT id FROM cuoco WHERE nome = 'Bruno' AND cognome = 'Barbieri'), '{/images/ricette/ZuppaDiPesce.jpeg}');
INSERT INTO ricetta (id, nome, descrizione, cuoco_id, urls_images) VALUES(nextval('ricetta_seq'), 'Torta Caprese', 'La nostra torta caprese è un classico dolce napoletano. Una torta al cioccolato e mandorle, senza farina, dal cuore morbido e dalla crosta croccante. Perfetta per i celiaci e per gli amanti del cioccolato.', (SELECT id FROM cuoco WHERE nome = 'Gennaro' AND cognome = 'Contaldo'), '{/images/ricette/TortaCaprese.jpeg}');

-- Inserimenti degli ingredienti
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Pomodoro');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Olio extravergine d oliva');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Parmigiano Reggiano');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Melanzane');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Ricotta Salata');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Riso');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Mozzarella');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Piselli');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Panna');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Pesce');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Cozze');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Vongole');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Mandorle');
INSERT INTO ingrediente (id, nome) VALUES(nextval('ingrediente_seq'), 'Cioccolato');

-- Inserimenti delle righe ricetta
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Pomodoro'), (SELECT id FROM ricetta WHERE nome = 'Pizza Margherita'), '200 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Olio extravergine d oliva'), (SELECT id FROM ricetta WHERE nome = 'Pizza Margherita'), 'q.b.');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Olio extravergine d oliva'), (SELECT id FROM ricetta WHERE nome = 'Spaghetti Carbonara'), '30 ml');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Parmigiano Reggiano'), (SELECT id FROM ricetta WHERE nome = 'Lasagna'), '50 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Parmigiano Reggiano'), (SELECT id FROM ricetta WHERE nome = 'Risotto ai Funghi'), '40 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Melanzane'), (SELECT id FROM ricetta WHERE nome = 'Pasta alla Norma'), '150 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Ricotta Salata'), (SELECT id FROM ricetta WHERE nome = 'Pasta alla Norma'), '50 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Riso'), (SELECT id FROM ricetta WHERE nome = 'Arancini di Riso'), '200 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Mozzarella'), (SELECT id FROM ricetta WHERE nome = 'Arancini di Riso'), '100 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Piselli'), (SELECT id FROM ricetta WHERE nome = 'Arancini di Riso'), '50 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Panna'), (SELECT id FROM ricetta WHERE nome = 'Panna Cotta al Caramello'), '500 ml');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Pesce'), (SELECT id FROM ricetta WHERE nome = 'Zuppa di Pesce'), '400 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Cozze'), (SELECT id FROM ricetta WHERE nome = 'Zuppa di Pesce'), '200 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Vongole'), (SELECT id FROM ricetta WHERE nome = 'Zuppa di Pesce'), '200 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Mandorle'), (SELECT id FROM ricetta WHERE nome = 'Torta Caprese'), '100 gr');
INSERT INTO riga_ricetta (id, ingrediente_id, ricetta_id, quantita) VALUES(nextval('riga_ricetta_seq'), (SELECT id FROM ingrediente WHERE nome = 'Cioccolato'), (SELECT id FROM ricetta WHERE nome = 'Torta Caprese'), '200 gr');
