insert into cuoco (id,nome,cognome,data_di_nascita,url_image) values(nextval('cuoco_seq'), 'Bruno', 'Barbieri','1962-01-12','/images/cuochi/Bruno-Barbieri.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) values (nextval('cuoco_seq'), 'Joe', 'Bastianich', '1968-09-17', '/images/cuochi/Joe-Bastianich.jpeg');
insert into cuoco (id,nome,cognome,data_di_nascita,url_image) values (nextval('cuoco_seq'), 'Antonino', 'Cannavacciuolo', '1975-11-21', '/images/cuochi/Antonino-Cannavacciuolo.jpeg');
insert into cuoco (id,nome,cognome,data_di_nascita,url_image) values(nextval('cuoco_seq'), 'Carlo', 'Cracco','1965-10-08','/images/cuochi/Carlo-Cracco.jpeg');
insert into cuoco (id,nome,cognome,data_di_nascita,url_image) values(nextval('cuoco_seq'), 'Gordon', 'Ramsay','1966-11-08','/images/cuochi/Gordon-Ramsay.jpeg');
INSERT INTO cuoco (id, nome, cognome, data_di_nascita, url_image) values (nextval('cuoco_seq'), 'Max', 'Mariola', '1976-05-18', '/images/cuochi/Max-Mariola.jpeg');

insert into ricetta (id, nome, descrizione, cuoco_id, urls_images) values (nextval('ricetta_seq'), 'Cacio e Pepe', 'La nostra cacio e pepe è un omaggio alla tradizione culinaria romana, un piatto che incarna l essenza della cucina italiana con pochi e semplici ingredienti. La pasta, al dente e avvolta in una crema vellutata di pecorino romano e pepe nero macinato al momento, trasporta i vostri sensi direttamente nelle stradine acciottolate di Roma. La combinazione di formaggio stagionato e piccante pepe nero crea un equilibrio di sapori robusti e intensi che si sposano armoniosamente con la pasta, regalando un esperienza gustativa autentica e appagante. Preparata con maestria e amore per la cucina tradizionale, la nostra cacio e pepe vi regalerà un viaggio sensoriale unico, dove ogni forchettata è un esplosione di gusto e nostalgia per i sapori genuini della cucina italiana', (select id from cuoco where nome = 'Joe' and cognome = 'Bastianich'),'{/images/ricette/CacioePepe.jpeg}');
insert into ricetta (id, nome, descrizione, cuoco_id, urls_images) values (nextval('ricetta_seq'), 'Lasagna', 'La nostra deliziosa lasagna è un tripudio di sapori italiani che conquista il palato ad ogni morso. Strati di pasta fresca si alternano con una salsa di pomodoro ricca e saporita, arricchita da carne macinata finemente aromatizzata con spezie mediterranee. Un abbraccio cremoso di besciamella avvolge il tutto, impreziosito da generose porzioni di formaggio mozzarella e parmigiano che si fondono in un mare di filantezza al primo taglio. Gli strati di verdure fresche donano freschezza e consistenza, creando un equilibrio perfetto di gusto e texture. Preparata con amore e passione, la nostra lasagna è un capolavoro culinario che conquisterà il cuore di ogni gourmet e delizierà le tavole di famiglie e amici. Semplice da preparare ma ricca di soddisfazioni, questa lasagna sarà la protagonista indiscussa delle vostre cene memorabili.', (select id from cuoco where nome = 'Bruno' and cognome = 'Barbieri'),'{/images/ricette/Lasagna.jpeg}');
insert into ricetta (id, nome, descrizione, cuoco_id, urls_images) values (nextval('ricetta_seq'), 'Tiramisù', 'Il nostro tiramisù è un autentico capolavoro della pasticceria italiana, un dolce che incanta i palati di chiunque lo assaggi. Strati di savoiardi imbevuti nel caffè si alternano con una crema di mascarpone delicata e vellutata, creando un equilibrio perfetto di dolcezza e intensità. Una leggera spolverata di cacao amaro completa questo dessert, regalando un contrasto piacevole di sapori e una nota finale elegante. Preparato con cura e passione, il nostro tiramisù è un omaggio alla tradizione culinaria italiana, capace di trasportare chi lo assapora in un viaggio di piacere e nostalgia. Perfetto da gustare in ogni occasione, questo tiramisù conquisterà il cuore di tutti gli amanti del buon cibo.', (select id from cuoco where nome = 'Carlo' and cognome = 'Cracco'),'{/images/ricette/Tiramisu.jpeg}');
insert into ricetta (id, nome, descrizione, cuoco_id, urls_images) values (nextval('ricetta_seq'), 'Risotto ai Funghi', 'Il nostro risotto ai funghi è una delizia culinaria che unisce la cremosità del riso Carnaroli con il gusto intenso dei funghi porcini. La base di brodo vegetale, arricchita da una selezione di erbe aromatiche, conferisce al piatto un sapore ricco e avvolgente. I funghi, delicatamente saltati in padella con aglio e prezzemolo, aggiungono profondità e complessità al risotto, creando un equilibrio perfetto di sapori terrosi e cremosità. La mantecatura finale con burro e parmigiano reggiano conferisce al piatto una consistenza vellutata e un sapore avvolgente che conquisterà ogni palato. Preparato con maestria e passione, il nostro risotto ai funghi è un esperienza gastronomica indimenticabile che vi farà innamorare della cucina italiana.', (select id from cuoco where nome = 'Gordon' and cognome = 'Ramsay'),'{/images/ricette/RisottoFunghi.jpeg}');
insert into ricetta (id, nome, descrizione, cuoco_id, urls_images) values (nextval('ricetta_seq'), 'Spaghetti Carbonara', 'La nostra versione della classica carbonara è un tripudio di sapori italiani che conquista il palato ad ogni forchettata. Spaghetti al dente si sposano con una crema vellutata di uova, pecorino romano e guanciale croccante, creando un equilibrio perfetto di gusto e consistenza. Il tocco finale di pepe nero macinato al momento aggiunge una nota di vivacità e intensità al piatto, rendendolo un esperienza gastronomica indimenticabile. Preparata con cura e passione, la nostra carbonara vi trasporterà direttamente nelle trattorie romane, regalandovi un viaggio sensoriale unico e appagante.', (select id from cuoco where nome = 'Joe' and cognome = 'Bastianich'), '{/images/ricette/Carbonara.jpeg}');
insert into ricetta (id, nome, descrizione, cuoco_id, urls_images) values (nextval('ricetta_seq'), 'Pizza Margherita', 'La nostra pizza Margherita è un omaggio alla tradizione napoletana, un simbolo della cucina italiana nel mondo intero. La base sottile e croccante, arricchita da una salsa di pomodoro fresco e basilico profumato, è coronata da generose fette di mozzarella di bufala che si fondono armoniosamente con gli altri ingredienti. Un filo d olio extravergine d oliva e una spolverata di sale marino completano questo capolavoro culinario, regalando un esplosione di sapori mediterranei ad ogni morso. Preparata con ingredienti di alta qualità e passione per la tradizione, la nostra pizza Margherita vi conquisterà con la sua semplicità e bontà, trasportandovi direttamente nei vicoli di Napoli.', (select id from cuoco where nome = 'Carlo' and cognome = 'Cracco'), '{/images/ricette/PizzaMargherita.jpeg}');
insert into ricetta (id, nome, descrizione, cuoco_id, urls_images) values (nextval('ricetta_seq'), 'Filetto di Manzo al Pepe Verde', 'Il nostro filetto di manzo al pepe verde è un piatto iconico che unisce la tenerezza della carne alla intensità del pepe verde. La carne, tagliata con precisione e cotta alla perfezione, si accoppia con una salsa cremosa e profumata al pepe verde che esalta il suo sapore e la sua morbidezza. Un contorno di verdure di stagione e patate al forno completa questo piatto, creando un equilibrio di gusto e texture che conquista ogni palato. Preparato con ingredienti freschi e di alta qualità, il nostro filetto di manzo al pepe verde è un esperienza culinaria indimenticabile che vi farà apprezzare la semplicità e leleganza della cucina italiana.', (select id from cuoco where nome = 'Bruno' and cognome = 'Barbieri'), '{/images/ricette/FilettoManzo.jpeg}');
insert into ricetta (id, nome, descrizione, cuoco_id, urls_images) values (nextval('ricetta_seq'), 'Gnocchi al Gorgonzola', 'I nostri gnocchi al gorgonzola sono un piatto irresistibile che unisce la delicatezza degli gnocchi alla cremosità e al sapore deciso del formaggio gorgonzola. Gli gnocchi, realizzati con patate fresche e farina di alta qualità, si sposano armoniosamente con una salsa cremosa di gorgonzola che avvolge ogni boccone in un abbraccio di gusto e piacere. Una spolverata di noci tritate aggiunge croccantezza e un tocco di sapore aggiuntivo al piatto, creando un equilibrio perfetto di sapori e consistenze. Preparati con cura e maestria, i nostri gnocchi al gorgonzola sono un esperienza gastronomica da gustare e condividere con chiunque ami la buona cucina italiana.', (select id from cuoco where nome = 'Gordon' and cognome = 'Ramsay'), '{/images/ricette/GnocchiGorgonzola.jpeg}');


insert into ingrediente(id,nome) values (nextval('ingrediente_seq'),'Pomodoro')
insert into ingrediente(id, nome) values (nextval('ingrediente_seq'),'Olio extravergine d oliva');
insert into ingrediente(id,nome) values (nextval('ingrediente_seq'),'Parmigiano Reggiano');

insert into riga_ricetta (id, ingrediente_id, ricetta_id, quantita) values (nextval('riga_ricetta_seq'),(select id from ingrediente where nome = 'Pomodoro'),(select id from ricetta where nome = 'Pizza Margherita'),'200 gr');
insert into riga_ricetta (id, ingrediente_id, ricetta_id, quantita) values (nextval('riga_ricetta_seq'),(select id from ingrediente where nome = 'Olio extravergine d oliva'),(select id from ricetta where nome = 'Pizza Margherita'),'q.b.');
insert into riga_ricetta (id, ingrediente_id, ricetta_id, quantita) values (nextval('riga_ricetta_seq'),(select id from ingrediente where nome = 'Olio extravergine d oliva'),(select id from ricetta where nome = 'Spaghetti Carbonara'),'30 ml');
insert into riga_ricetta (id, ingrediente_id, ricetta_id, quantita) values (nextval('riga_ricetta_seq'),(select id from ingrediente where nome = 'Parmigiano Reggiano'),(select id from ricetta where nome = 'Lasagna'),'50 gr');
insert into riga_ricetta (id, ingrediente_id, ricetta_id, quantita) values (nextval('riga_ricetta_seq'),(select id from ingrediente where nome = 'Parmigiano Reggiano'),(select id from ricetta where nome = 'Risotto ai Funghi'),'40 gr');
